// All roles with their abilities and colors
export const ROLES = [
  {
    id: "crewmate",
    name: "Crewmate",
    team: "crew",
    color: "#00ffff",
    glow: "0 0 30px #00ffff",
    icon: "user",
    description: "Complete tasks and find the impostors before it&apos;s too late.",
    abilities: ["Complete Tasks", "Report Bodies", "Call Meetings", "Vote"],
  },
  {
    id: "impostor",
    name: "Impostor",
    team: "impostor",
    color: "#ff0033",
    glow: "0 0 30px #ff0033",
    icon: "skull",
    description: "Eliminate crewmates and sabotage the ship without getting caught.",
    abilities: ["Kill", "Sabotage", "Vent", "Fake Tasks"],
  },
  {
    id: "engineer",
    name: "Engineer",
    team: "crew",
    color: "#ffaa00",
    glow: "0 0 30px #ffaa00",
    icon: "wrench",
    description: "Can use vents to travel quickly and fix sabotages faster.",
    abilities: ["Use Vents", "Fast Repairs", "Complete Tasks"],
  },
  {
    id: "guardian",
    name: "Guardian Angel",
    team: "crew",
    color: "#66ffff",
    glow: "0 0 30px #66ffff",
    icon: "shield",
    description: "After death, can protect one living player from being killed.",
    abilities: ["Protect Players", "Spectate", "Guide Crew"],
  },
  {
    id: "medic",
    name: "Medic",
    team: "crew",
    color: "#00ff66",
    glow: "0 0 30px #00ff66",
    icon: "heart",
    description: "Can check vitals and revive one dead player per game.",
    abilities: ["Check Vitals", "Revive", "Complete Tasks"],
  },
  {
    id: "hacker",
    name: "Hacker",
    team: "crew",
    color: "#00cc00",
    glow: "0 0 30px #00cc00",
    icon: "terminal",
    description: "Can access admin table and security from anywhere.",
    abilities: ["Remote Admin", "Remote Cams", "Complete Tasks"],
  },
  {
    id: "sheriff",
    name: "Sheriff",
    team: "crew",
    color: "#ffcc00",
    glow: "0 0 30px #ffcc00",
    icon: "badge",
    description: "Can kill impostors, but dies if they kill a crewmate.",
    abilities: ["Kill Impostors", "Risk Death", "Complete Tasks"],
  },
  {
    id: "jester",
    name: "Jester",
    team: "neutral",
    color: "#ff66ff",
    glow: "0 0 30px #ff66ff",
    icon: "mask",
    description: "Wins if they get voted out. Cannot kill or be killed.",
    abilities: ["Act Suspicious", "Win by Ejection", "Chaos"],
  },
  {
    id: "phantom",
    name: "Phantom",
    team: "crew",
    color: "#9999ff",
    glow: "0 0 30px #9999ff",
    icon: "ghost",
    description: "Turns invisible for a short time when standing still.",
    abilities: ["Invisibility", "Stealth", "Complete Tasks"],
  },
  {
    id: "snitch",
    name: "Snitch",
    team: "crew",
    color: "#ff9900",
    glow: "0 0 30px #ff9900",
    icon: "eye",
    description: "Sees impostor names when tasks are almost complete, but becomes visible to impostors.",
    abilities: ["See Impostors", "High Risk", "Complete Tasks"],
  },
  {
    id: "tracker",
    name: "Tracker",
    team: "crew",
    color: "#33ff99",
    glow: "0 0 30px #33ff99",
    icon: "crosshair",
    description: "Can track one player&apos;s location on the map.",
    abilities: ["Track Players", "Hunt", "Complete Tasks"],
  },
  {
    id: "morphling",
    name: "Morphling",
    team: "impostor",
    color: "#cc00ff",
    glow: "0 0 30px #cc00ff",
    icon: "repeat",
    description: "Can transform into another player to frame them.",
    abilities: ["Morph", "Frame", "Kill"],
  },
  {
    id: "timekeeper",
    name: "Timekeeper",
    team: "crew",
    color: "#6699ff",
    glow: "0 0 30px #6699ff",
    icon: "clock",
    description: "Can freeze time for all players except themselves briefly.",
    abilities: ["Freeze Time", "Investigate", "Complete Tasks"],
  },
  {
    id: "spectator",
    name: "Spectator",
    team: "neutral",
    color: "#888888",
    glow: "0 0 30px #888888",
    icon: "eye",
    description: "Cannot participate but can watch and chat with dead players.",
    abilities: ["Watch Game", "Ghost Chat", "Free Roam"],
  },
] as const

export type RoleId = (typeof ROLES)[number]["id"]

// All tasks with their mini-games
export const TASKS = [
  {
    id: "wires",
    name: "Fix Wiring",
    location: "Electrical",
    duration: 3000,
    type: "wires",
    description: "Connect matching colored wires",
    icon: "zap",
  },
  {
    id: "switches",
    name: "Flip Switches",
    location: "Electrical",
    duration: 2000,
    type: "switches",
    description: "Match the switch pattern shown above",
    icon: "toggle-right",
  },
  {
    id: "keypad",
    name: "Enter Code",
    location: "Admin",
    duration: 4000,
    type: "keypad",
    description: "Enter the 4-digit code displayed",
    icon: "hash",
  },
  {
    id: "sliders",
    name: "Adjust Sliders",
    location: "Reactor",
    duration: 3500,
    type: "sliders",
    description: "Set all sliders to their target values",
    icon: "sliders",
  },
  {
    id: "download",
    name: "Download Data",
    location: "Communications",
    duration: 5000,
    type: "progress",
    description: "Wait for the download to complete",
    icon: "download",
  },
  {
    id: "upload",
    name: "Upload Data",
    location: "Admin",
    duration: 5000,
    type: "progress",
    description: "Wait for the upload to complete",
    icon: "upload",
  },
  {
    id: "fuel",
    name: "Fuel Engines",
    location: "Storage",
    duration: 4000,
    type: "fuel",
    description: "Hold to fill the fuel tank",
    icon: "droplet",
  },
  {
    id: "maze",
    name: "Navigate Maze",
    location: "Navigation",
    duration: 6000,
    type: "maze",
    description: "Guide the dot through the maze",
    icon: "navigation",
  },
  {
    id: "pattern",
    name: "Match Pattern",
    location: "Security",
    duration: 4000,
    type: "pattern",
    description: "Repeat the flashing pattern",
    icon: "grid",
  },
  {
    id: "asteroids",
    name: "Clear Asteroids",
    location: "Weapons",
    duration: 5000,
    type: "asteroids",
    description: "Shoot all the approaching asteroids",
    icon: "target",
  },
  {
    id: "swipe",
    name: "Swipe Card",
    location: "Admin",
    duration: 3000,
    type: "swipe",
    description: "Swipe the card at the right speed",
    icon: "credit-card",
  },
  {
    id: "temperature",
    name: "Calibrate Temperature",
    location: "Reactor",
    duration: 3500,
    type: "temperature",
    description: "Adjust to the target temperature",
    icon: "thermometer",
  },
  {
    id: "telescope",
    name: "Align Telescope",
    location: "Observatory",
    duration: 4000,
    type: "telescope",
    description: "Center the target in the viewfinder",
    icon: "compass",
  },
  {
    id: "garbage",
    name: "Empty Garbage",
    location: "Cafeteria",
    duration: 3000,
    type: "garbage",
    description: "Hold the lever to empty trash",
    icon: "trash",
  },
  {
    id: "steering",
    name: "Stabilize Steering",
    location: "Navigation",
    duration: 3500,
    type: "steering",
    description: "Keep the crosshair centered",
    icon: "move",
  },
  {
    id: "power",
    name: "Divert Power",
    location: "Electrical",
    duration: 2500,
    type: "power",
    description: "Redirect power to the indicated room",
    icon: "battery-charging",
  },
] as const

export type TaskId = (typeof TASKS)[number]["id"]

// All maps with their layouts
export const MAPS = [
  {
    id: "starship",
    name: "Starship",
    description: "The classic spacecraft with multiple levels",
    color: "#00ffff",
    rooms: [
      "Cafeteria",
      "Medbay",
      "Upper Engine",
      "Lower Engine",
      "Security",
      "Reactor",
      "Electrical",
      "Storage",
      "Admin",
      "Weapons",
      "Shields",
      "Communications",
      "Navigation",
      "O2",
    ],
    vents: [
      ["Medbay", "Electrical"],
      ["Security", "Medbay"],
      ["Reactor", "Upper Engine"],
      ["Lower Engine", "Reactor"],
      ["Shields", "Navigation"],
      ["Admin", "Cafeteria"],
    ],
    sabotages: ["Reactor Meltdown", "O2 Depletion", "Lights", "Comms"],
  },
  {
    id: "research_lab",
    name: "Research Lab",
    description: "A sprawling underground research facility",
    color: "#00ff66",
    rooms: [
      "Lobby",
      "Laboratory",
      "Specimen",
      "Office",
      "Greenhouse",
      "Server Room",
      "Cafeteria",
      "Decontamination",
      "Storage",
      "Reactor",
      "Medical",
      "Launchpad",
    ],
    vents: [
      ["Laboratory", "Specimen"],
      ["Office", "Greenhouse"],
      ["Server Room", "Storage"],
      ["Reactor", "Decontamination"],
    ],
    sabotages: ["Biohazard", "Power Grid", "Lights", "Doors"],
  },
  {
    id: "cyber_city",
    name: "Cyber City",
    description: "A neon-lit cyberpunk megastructure",
    color: "#ff00ff",
    rooms: [
      "Plaza",
      "Market",
      "Tower",
      "Underground",
      "Arcade",
      "Police Station",
      "Hospital",
      "Factory",
      "Docks",
      "Penthouse",
      "Subway",
      "Warehouse",
    ],
    vents: [
      ["Underground", "Subway"],
      ["Tower", "Penthouse"],
      ["Factory", "Warehouse"],
      ["Arcade", "Market"],
    ],
    sabotages: ["Blackout", "Traffic", "Lockdown", "Fire"],
  },
  {
    id: "desert_outpost",
    name: "Desert Outpost",
    description: "A remote mining facility in the wasteland",
    color: "#ff9900",
    rooms: [
      "Command",
      "Mines",
      "Refinery",
      "Barracks",
      "Garage",
      "Workshop",
      "Solar Array",
      "Water Treatment",
      "Communications",
      "Landing Pad",
    ],
    vents: [
      ["Mines", "Refinery"],
      ["Barracks", "Workshop"],
      ["Solar Array", "Communications"],
    ],
    sabotages: ["Sandstorm", "Water Supply", "Solar Failure", "Doors"],
  },
  {
    id: "underwater_base",
    name: "Underwater Base",
    description: "A deep sea research station",
    color: "#0066ff",
    rooms: [
      "Airlock",
      "Moon Pool",
      "Observation",
      "Quarters",
      "Lab",
      "Control Room",
      "Cargo Bay",
      "Life Support",
      "Generator",
      "Dive Bay",
      "Med Bay",
      "Cafeteria",
    ],
    vents: [
      ["Moon Pool", "Dive Bay"],
      ["Lab", "Control Room"],
      ["Generator", "Life Support"],
      ["Cargo Bay", "Airlock"],
    ],
    sabotages: ["Hull Breach", "Pressure", "Lights", "Oxygen"],
  },
  {
    id: "sky_fortress",
    name: "Sky Fortress",
    description: "A floating military installation in the clouds",
    color: "#66ffff",
    rooms: [
      "Bridge",
      "Hangar",
      "Armory",
      "Barracks",
      "Engine Room",
      "Observation Deck",
      "Mess Hall",
      "Medical Bay",
      "Communications",
      "Brig",
      "Training Room",
      "Control Tower",
    ],
    vents: [
      ["Hangar", "Engine Room"],
      ["Armory", "Training Room"],
      ["Bridge", "Control Tower"],
      ["Brig", "Barracks"],
    ],
    sabotages: ["Engine Failure", "Anti-Air", "Lockdown", "Comms"],
  },
] as const

export type MapId = (typeof MAPS)[number]["id"]

// Cosmetics
export const HATS = [
  { id: "none", name: "None", icon: null },
  { id: "crown", name: "Crown", icon: "crown" },
  { id: "antenna", name: "Antenna", icon: "radio" },
  { id: "flower", name: "Flower", icon: "flower" },
  { id: "hardhat", name: "Hard Hat", icon: "hard-hat" },
  { id: "halo", name: "Halo", icon: "circle" },
  { id: "horns", name: "Devil Horns", icon: "flame" },
  { id: "headphones", name: "Headphones", icon: "headphones" },
  { id: "beanie", name: "Beanie", icon: "cloud" },
  { id: "tophat", name: "Top Hat", icon: "box" },
  { id: "ninja", name: "Ninja Mask", icon: "wind" },
  { id: "viking", name: "Viking Helmet", icon: "shield" },
] as const

export const SKINS = [
  { id: "none", name: "None" },
  { id: "astronaut", name: "Astronaut" },
  { id: "mech", name: "Mech Suit" },
  { id: "hazmat", name: "Hazmat" },
  { id: "military", name: "Military" },
  { id: "police", name: "Police" },
  { id: "doctor", name: "Doctor" },
  { id: "captain", name: "Captain" },
  { id: "ninja", name: "Ninja" },
  { id: "scientist", name: "Scientist" },
] as const

// Sabotage data
export const SABOTAGES = [
  {
    id: "reactor",
    name: "Reactor Meltdown",
    icon: "alert-triangle",
    color: "#ff0033",
    timer: 45,
    description: "Meltdown in progress! Two players must hold pads to stop it.",
    locations: ["Reactor"],
    critical: true,
  },
  {
    id: "o2",
    name: "O2 Depletion",
    icon: "wind",
    color: "#00ff66",
    timer: 30,
    description: "Oxygen depleting! Enter codes in Admin and O2 to restore.",
    locations: ["Admin", "O2"],
    critical: true,
  },
  {
    id: "lights",
    name: "Lights Sabotage",
    icon: "zap-off",
    color: "#ffff00",
    timer: null,
    description: "Vision reduced! Flip switches in Electrical to restore.",
    locations: ["Electrical"],
    critical: false,
  },
  {
    id: "comms",
    name: "Communications",
    icon: "wifi-off",
    color: "#0066ff",
    timer: null,
    description: "Comms disabled! Adjust dial in Communications to restore.",
    locations: ["Communications"],
    critical: false,
  },
  {
    id: "doors",
    name: "Door Lockdown",
    icon: "lock",
    color: "#ff6600",
    timer: 10,
    description: "Doors locked! Wait for automatic unlock.",
    locations: [],
    critical: false,
  },
] as const

// Game settings defaults
export const DEFAULT_SETTINGS = {
  maxPlayers: 10,
  impostors: 2,
  confirmEjects: true,
  emergencyMeetings: 1,
  emergencyCooldown: 15,
  discussionTime: 30,
  votingTime: 60,
  anonymousVotes: false,
  playerSpeed: 1.0,
  crewVision: 1.0,
  impostorVision: 1.5,
  killCooldown: 30,
  killDistance: "medium",
  taskBarUpdates: "always",
  visualTasks: true,
  commonTasks: 2,
  longTasks: 3,
  shortTasks: 5,
}
